# Generated by Django 4.1 on 2022-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=1024, null=True)),
                ('cargo', models.CharField(blank=True, max_length=1024, null=True)),
                ('idade', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionarios',
                'ordering': ['-id'],
            },
        ),
    ]
