# Generated by Django 4.1 on 2022-08-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_produto_preco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidate',
            new_name='quantidade',
        ),
    ]
