# Generated by Django 4.1 on 2022-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_quantidate_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
